name: Coveralls

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

jobs:
  nodejs:
    name: Coveralls Upload
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node Version
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.5
      - name: npm install
        run: npm install
        working-directory: ./
      - name: npm build
        run: npm build
        working-directory: ./
      - name: npm test
        run: npm test
        working-directory: ./
      - name: npm coverage
        run: npm test -- --coverage
        working-directory: ./
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.1
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
